AVEVA/CONNECT-data-services-developer-docs

- content/adh-content-portal-overview.md
- content/overview/get-started/aveva-cnnxt/cnnxt-mgmt/create-folder.md
- content/overview/what-does-adh-do.md
- content/overview/what-is-adh.md
- content/overview/who-uses-adh.md
Published version is here: https://osisoft-dev.zoominsoftware.io/bundle/data-hub-pbi-344006-adh-service-description/page/adh-content-portal-overview.html
@afloresOSI you may want to check the link to the service description at the end of what-is-adh to see what you think about the wording and placement.
> service description

- content/api-reference/ocs-api-reference.md
- content/developer-guide/data-views-dev/get-data-view-data/quick-start-get-data-view-data.md
- content/developer-guide/sequential-data-store-dev/sds-read-data.md
added response format section to ocs-api-reference.md. removed specifics from other 2 docs, and added a link to details.
> Response format

- content/add-organize-data/organize-data/assets/remove-asset-types.md
- content/add-organize-data/organize-data/assets/remove-assets.md
- content/toc.yml
> Remove Asset/Asset Types

- content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/af-data-transferred.md
- content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
- content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/start-transfer.md
- content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
- content/overview/get-started/connections/gs-pi-to-ocs-connection.md
- content/set-up/namespaces/namespaces-concept.md
- content/toc.yml
Test publish: https://aveva-dev.zoominsoftware.io/bundle/data-hub-pbi-375556-adh-transfer-org/page/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/lp-transfer.html
> Pbi 375556 adh transfer org

- content/add-organize-data/collect-data/software-mgmt/base-configurations.md
- content/add-organize-data/collect-data/software-mgmt/configure-edge-system.md
- content/add-organize-data/collect-data/software-mgmt/deploy-configuration.md
- content/add-organize-data/collect-data/software-mgmt/deploy-module.md
- content/add-organize-data/collect-data/software-mgmt/software-management.md
- content/toc.yml
> Victoria m1 merge

- content/add-organize-data/collect-data/software-mgmt/base-configurations.md
- content/add-organize-data/collect-data/software-mgmt/view-edge-system.md
added info about assisted search
> Search bar update

- content/overview/get-started/introduction-portal-interface.md
added context to intro for home page contents.
> Home page update

- content/add-organize-data/organize-data/assets/create-an-asset.md
adding integer feature to assets
> 400410 asset status integers

- content/overview/get-started/aveva-cnnxt/manage-users-connect.md
- content/overview/get-started/resource-usage.md
- content/set-up/groups/groups-procedure.md
> Embedded videos

- content/api-reference/assets/assets-asset-types.md
- content/api-reference/assets/assets-assets-search.md
- content/api-reference/assets/assets-assets.md
- content/api-reference/assets/assets-resolved-asset.md
- content/communities/community-communities-page.md
- content/communities/community-view-shared-data.md
> Docupipe merge 050923

- content/developer-guide/omf-dev/omf-ingress-specification.md
- content/developer-guide/sequential-data-store-dev/sds-write-data.md
- content/overview/get-started/gs-ingress.md
The dev guide changes are only to fix a few formatting issues.
> Pbi 393523 gs ingress

- content/api-reference/sequential-data-store/sds-bulk.md
- content/api-reference/sequential-data-store/toc.yml
This adds a page for the bulk streams endpoint, and adds a table of contents reference for the same.
> Added bulk/streams endpoint

- content/add-organize-data/organize-data/change-data-broker/change-broker.md
- content/add-organize-data/organize-data/change-data-broker/stream-updates.md
- content/toc.yml
first draft for lighthouse release.
> change broker draft

- content/api-reference/streaming-updates/streaming-updates.md
Updating term 'streaming updates' to 'Change Broker' per Alex. Also added a couple details to the intro.
> Renaming of streaming updates service

- content/api-reference/change-broker/change-broker.md
- content/api-reference/software-management/software-mgmt-api-overview.md
updates titles to remove preview. Fixed some capitalization errors.
> title updates

- content/api-reference/toc.yml
> TOC update

- content/api-reference/data-views/data-views-access-control.md
Fix for [ADO 3013854](https://dev.azure.com/AVEVA-VSTS/Cloud%20Platform/_workitems/edit/3013854).
> Docupipe data views 2 28 24

- content/api-reference/sequential-data-store/sds-bulk.md
Fixed table and added slash to GET URL
> P2 feedback updates

- content/api-reference/assets/assets-asset-status.md
- content/api-reference/assets/assets-asset-types.md
- content/api-reference/assets/assets-assets-search.md
- content/api-reference/assets/assets-assets.md
- content/api-reference/assets/assets-resolved-asset.md
- content/api-reference/sequential-data-store/sds-access-control-list.md
- content/api-reference/sequential-data-store/sds-bulk.md
- content/api-reference/sequential-data-store/sds-stream-data.md
- content/api-reference/sequential-data-store/sds-streams.md
- content/api-reference/sequential-data-store/toc.yml
- content/api-reference/tenant/tenant-namespace.md
- content/api-reference/tenant/tenant-namespaces.md
- content/api-reference/tenant/toc.yml
- content/developer-guide/sequential-data-store-dev/read-data/sds-data-query-methods.md
- content/developer-guide/sequential-data-store-dev/sds-read-data.md
- content/developer-guide/sequential-data-store-dev/toc.yml
- content/external-references/datacalls.yaml
Merging Assets updates for WI 3703812
> 3703812 - Assets API update

- content/external-references/changebroker-summaries.yml
> correcting indent

- content/api-reference/toc.yml
- content/api-reference/virtual-table-sharing/toc.yml
- content/api-reference/virtual-table-sharing/virtual-table-api-overview.md
- content/api-reference/virtual-table-sharing/virtual-table-sharing-access-control.md
- content/api-reference/virtual-table-sharing/virtual-table-sharing-materialization.md
- content/api-reference/virtual-table-sharing/virtual-table-sharing-sharing.md
Merging virtual tables API docs
> Docu pipe virtual table sharing
